# Generated by Django 4.1.3 on 2022-11-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_auto_20190815_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_curta',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_longa',
            new_name='ingredientes',
        ),
    ]
