# Generated by Django 4.1.3 on 2022-11-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_rename_descricao_curta_produto_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
    ]
